In [77]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy
import matplotlib.pyplot as plt
data = pd.read_csv('Sales_add.csv')
data

Month      Region      Manager  Sales_before_digital_add(in $)  \
0    Month-1  Region - A  Manager - A                          132921   
1    Month-2  Region - A  Manager - C                          149559   
2    Month-3  Region - B  Manager - A                          146278   
3    Month-4  Region - B  Manager - B                          152167   
4    Month-5  Region - C  Manager - B                          159525   
5    Month-6  Region - A  Manager - B                          137163   
6    Month-7  Region - C  Manager - C                          130625   
7    Month-8  Region - A  Manager - A                          131140   
8    Month-9  Region - B  Manager - C                          171259   
9   Month-10  Region - C  Manager - B                          141956   
10  Month-11  Region - B  Manager - C                          159339   
11  Month-12  Region - A  Manager - A                          178939   
12  Month-13  Region - B  Manager - A                          145062   
13  Month-14  Region - A  Manager - A                          151514   
14  Month-15  Region - C  Manager - A                          147463   
15  Month-16  Region - A  Manager - B                          177195   
16  Month-17  Region - A  Manager - C                          140862   
17  Month-18  Region - C  Manager - B                          167996   
18  Month-19  Region - B  Manager - A                          132135   
19  Month-20  Region - A  Manager - B                          152493   
20  Month-21  Region - B  Manager - A                          147425   
21  Month-22  Region - A  Manager - C                          130263   

    Sales_After_digital_add(in $)  
0                          270390  
1                          223334  
2                          244243  
3                          231808  
4                          258402  
5                          256948  
6                          222106  
7                          230637  
8                          226261  
9                          193735  
10                         203175  
11                         276279  
12                         205180  
13                         253131  
14                         229336  
15                         187305  
16                         234908  
17                         191517  
18                         227040  
19                         212579  
20                         263388  
21                         243020

In [78]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


In [79]:
data.isna().sum()

Month                             0
Region                            0
Manager                           0
Sales_before_digital_add(in $)    0
Sales_After_digital_add(in $)     0
dtype: int64

In [80]:
data.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

In [81]:
data.mean()

Sales_before_digital_add(in $)    149239.954545
Sales_After_digital_add(in $)     231123.727273
dtype: float64

In [82]:
data.median()

Sales_before_digital_add(in $)    147444.0
Sales_After_digital_add(in $)     229986.5
dtype: float64

In [84]:
data.shape

(22, 5)

In [85]:
data.std()

Sales_before_digital_add(in $)    14844.042921
Sales_After_digital_add(in $)     25556.777061
dtype: float64

## 1.


### Null Hypothesis:
   **The Sales after stepping into digital marketing are same as or less than the sales before**


### Alternate Hypothesis:
 **The sales after stepping into digital marketing is greater than sales before**

In [143]:
from scipy import stats
from scipy.stats import norm
from scipy.stats import ttest_ind

In [144]:
B=data['Sales_before_digital_add(in $)']
A=data['Sales_After_digital_add(in $)']

In [145]:
ttest,pval =stats.ttest_rel(B,A)

In [146]:
print("The P-Value is", pval)
print("The T-Value is", abs(ttest))

The P-Value is 6.336667004575778e-11
The T-Value is 12.09070525287017


In [147]:
if pval <0.5:
    print("We reject the null hypothesis, that menans the sales improved")
else:
    print("We accept the null hypothesis, that means the sales did not improve")

We reject the null hypothesis, that menans the sales improved


***
## Result:: As the null hypothesis is rejected we can see that there is increase in sales of the company after stepping into digital marketing.
***

# 2.

### Null Hypothesis:
   **There is NO significant dependency between the features 'Region' and 'Manager'**


### Alternate Hypothesis:
 **There is significant amount of dependency between the features 'Region' and 'Manager'**

In [148]:
pd.crosstab(data.Region,data.Manager)

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [149]:
from scipy.stats import chi2_contingency
val=chi2_contingency(pd.crosstab(data.Region,data.Manager))
val

(3.050566893424036,
 0.5493991051158094,
 4,
 array([[4.09090909, 3.18181818, 2.72727273],
        [2.86363636, 2.22727273, 1.90909091],
        [2.04545455, 1.59090909, 1.36363636]]))

In [155]:
Chival=val[0]
print("The Chi-Square test statistics value is:",Chival)

The Chi-Square test statistics value is: 3.050566893424036


In [151]:
pvalue=val[1]
print("The P-value is:",pvalue)

The P-value is: 0.5493991051158094


In [156]:
DF=val[2]
print("The Degree of Freedom is:",DF)


The Degree of Freedom is: 4


In [153]:
print("The Expected value is:\n", val[3])

The Expected value is:
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]


In [164]:
cval=chi2.ppf(q=1-0.05,df=DF)
print("The Critical value is:\n",cval)

The Critical value is:
 9.487729036781154


In [167]:
if pvalue <0.5:
    print("We reject null hypothesis,There is significant amount of dependency between the features 'Region' and 'Manager'")
else:
    print("We accept null hypothesis,There is NO significant amount of dependency between the features 'Region' and 'Manager'")
if Chival>cval:
     print("There is Relashinship")
else:
     print("There is NO Relationship")


We accept null hypothesis,There is NO significant amount of dependency between the features 'Region' and 'Manager'
There is NO Relationship


***
## Result:: As we can't reject null hypothesis we can conclude that the features "Region" and "Manager" are Independent.
***